# Generated by Django 6.0.6 on 2026-07-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('admission', 'Admission'), ('fees', 'Fees'), ('courses', 'Courses'), ('hostel', 'Hostel'), ('placements', 'Placements'), ('library', 'Library'), ('general', 'General')], max_length=30)),
                ('keywords', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
